### ISSUE TITLE
Sending image in chat fom attachment button

### ISSUE THREAD

**Issue by attrib75** [rlingineni/Xamarin.Forms-ChatMessenger#2]
Great library.  Do you know how to implement public override async void PressedAccessoryButton(UIButton sender)?  For when the user presses the attach button to send an attachment?  (I uncommented the part where it hides the attach button).  Thanks

**Comment by attrib75** [comment]
Actually I figured it out.  I can contribute to the example if you'd like.

**Comment by rlingineni** [comment]
Yes please, could you make a pull request
